title: DIY Everyhing
author: matejanez
theme: minima
email: mjanez@test.com
description: > # this means to ignore newlines until "baseurl:"
  Blog about DIY, electronics, programming, home automation, tutorials, ...
# social links
twitter_username: mjanez # DO NOT include the @ character, or else the build will fail!
github_username:  mjanez # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
